### ISSUE TITLE
BTVaultManagementViewController.m:103:42 'setNetworkActivityIndicatorVisible:' is deprecated: first deprecated in iOS 13.0

### ISSUE THREAD

**Issue by andrii-lisovskiy** [braintree/braintree-ios-drop-in#421] opened 2023-08-03 11:53 UTC
### Braintree Drop-in SDK Version

9.8.2

### Environment

Both

### Xcode Version

14.3.1

### OS Version & Device

iPhone 13 Pro - iOS 16.6

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

Build Failed because of next issue:

`/Pods/BraintreeDropIn/Sources/BraintreeDropIn/BTVaultManagementViewController.m:103:42 'setNetworkActivityIndicatorVisible:' is deprecated: first deprecated in iOS 13.0 - Provide a custom network activity UI in your app if desired.
`

<img width="366" alt="Screenshot 2023-08-03 at 13 42 39" src="https://github.com/braintree/braintree-ios-drop-in/assets/69899396/32b8a79f-885c-4976-8b2c-b45eb592b3a6">
<img width="1140" alt="Screenshot 2023-08-03 at 13 51 32" src="https://github.com/braintree/braintree-ios-drop-in/assets/69899396/0049091b-fcc2-492c-a3a5-351ef766afa5">

### To reproduce

1. Set minimum iOS version 13.0 in Project Target and Podfile
2. Install pods
2. Run app

### Expected behavior

Build Successed

### Screenshots

<img width="697" alt="Screenshot 2023-08-03 at 13 46 56" src="https://github.com/braintree/braintree-ios-drop-in/assets/69899396/72b675b9-f7b9-44f0-8009-3753fb69e630">
<img width="669" alt="Screenshot 2023-08-03 at 13 47 30" src="https://github.com/braintree/braintree-ios-drop-in/assets/69899396/eea57978-352d-4291-a0c5-be4702dcc254">
<img width="604" alt="Screenshot 2023-08-03 at 13 47 43" src="https://github.com/braintree/braintree-ios-drop-in/assets/69899396/79f29ac0-c3fb-45ef-9ce5-b64e173392b7">
<img width="877" alt="Screenshot 2023-08-03 at 13 49 16" src="https://github.com/braintree/braintree-ios-drop-in/assets/69899396/f5dd5fba-52d2-4d2e-a29d-125c2cce0dff">

**Comment by jaxdesmarais** [comment] 2023-08-04 16:13
Hello @andrii-lisovskiy -

Thanks for reporting this issue. I have created internal ticket DTBTSDK-2899 to track this work on our end. Are you able to share your setting for "Treat Warnings as Errors" in your Build Settings?

**Comment by jaxdesmarais** [comment] 2023-08-04 16:38
Hello again @andrii-lisovskiy -

I believe this issue may be with the compiler still attempting to compile the code with the `if/else` statements. I've created a branch called `update-to-use-compiler-flags` that replaces these with macros. You can see the diff of the changes [here](https://github.com/braintree/braintree-ios-drop-in/compare/update-to-use-compiler-flags). 

Are you able to pull in that branch locally and let me know if this resolves the issue you are seeing? If so, I can work on getting a PR up for this update. Additionally if you run into any new errors please let me know.

**Comment by rishbaranwal** [comment] 2023-08-15 10:56
@jaxdesmarais Please update here as well(refer attach screenshot), also kindly let me know by when the P R Request will get merge and new version available on Cocoapods
<img width="1854" alt="Screenshot 2023-08-15 at 4 23 58 PM" src="https://github.com/braintree/braintree-ios-drop-in/assets/5096659/943d0ddf-26dd-45f7-824b-a15701183b5c">

**Comment by rishbaranwal** [comment] 2023-08-15 11:08
@jaxdesmarais  Please make sure to compile before raising the PR...as I can see the same error on two more places

**Comment by rishbaranwal** [comment] 2023-08-16 15:28
It's simply occurring when we compile on XCode 14.3.1, also make sure the Swift Language version is 5 or greater

**Comment by andrii-lisovskiy** [comment] 2023-08-17 08:13
@jaxdesmarais
<img width="1131" alt="Screenshot 2023-08-17 at 10 11 57" src="https://github.com/braintree/braintree-ios-drop-in/assets/69899396/4228d84f-2769-482c-8878-af5fa47175b5">

**Comment by andrii-lisovskiy** [comment] 2023-08-17 08:35
> Hello again @andrii-lisovskiy -
> 
> I believe this issue may be with the compiler still attempting to compile the code with the `if/else` statements. I've created a branch called `update-to-use-compiler-flags` that replaces these with macros. You can see the diff of the changes [here](https://github.com/braintree/braintree-ios-drop-in/compare/update-to-use-compiler-flags).
> 
> Are you able to pull in that branch locally and let me know if this resolves the issue you are seeing? If so, I can work on getting a PR up for this update. Additionally if you run into any new errors please let me know.

Hello @jaxdesmarais, I was able to build app with your PR. Looks like your fix worked for me. Please, update me when it will be part of main branch. Thanks!

**Comment by jaxdesmarais** [comment] 2023-08-17 19:24
Hello @rishbaranwal -

I am not able to reproduce these warnings in our [Demo app](https://github.com/braintree/braintree-ios-drop-in/tree/main/Demo) nor in a fresh cocoapods project on Xcode 14.3.1 and Swift 5+. There must be a setting you are using to surface these errors as they are not surfaced by default. If you are able to share that information we'd be happy to update the remaining warnings and open a PR to resolve this issue for you and @andrii-lisovskiy.

Thanks for your support so we can get this fixed for you.

**Comment by jaxdesmarais** [comment] 2023-08-23 18:13
Hey @rishbaranwal -

Not sure if you saw my last message. We are not able to reproduce these warnings in our [Demo app](https://github.com/braintree/braintree-ios-drop-in/tree/main/Demo) nor in a fresh cocoapods project on Xcode 14.3.1 and Swift 5+. There must be a setting you are using to surface these errors as they are not surfaced by default. Alternatively if you want to share a small sample app with the warnings we'd be happy to resolve them all in 1 go, but currently are unable to reproduce.

**Comment by jaxdesmarais** [comment] 2023-09-06 15:46
Hey @andrii-lisovskiy -

Thanks again for your patience! This was released in version [9.10.0](https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.10.0) of the SDK. Once you update please let us know if you are running into any issues. I'll close this issue for now, but please feel free to respond and I can reopen if needed.

**Closed by jaxdesmarais** 2023-09-06 15:46 UTC
