### ISSUE TITLE
Cell height is too small on Select Payment Method screen

### ISSUE THREAD

**Issue by bornaMobiLabs** [braintree/braintree-ios-drop-in#75] opened 2018-01-30 19:39 UTC
### General information

* SDK/Library version: 5.3
* Environment: Sandbox and Production
* iOS Version and Device: iOS 11.2.5 on iPhone 7
* Integration type and version: Carthage 0.28 

### Issue description

On Select Payment Method screen cell height is smaller then it should be. It is harder for user to pick a payment method.

![img_8948](https://user-images.githubusercontent.com/18572289/35587196-57c980ee-05fd-11e8-9f58-b7830a7910e4.PNG)

**Comment by demerino** [comment] 2018-01-30 23:39
@bornaMobiLabs Can you verify that you're on `Drop-in` 5.3?

I ask because I'm unable to reproduce this issue on a device running 11.2.5 and Drop-in 5.3.

Similar issues were impacting iOS 11 devices, but should be fixed in 5.3

**Comment by bluk** [comment] 2018-02-05 22:32
I believe this issue was fixed. If you are still encountering this on `Drop-in 5.3`, please leave a comment and we can re-open the issue. Thanks.

**Closed by bluk** 2018-02-05 22:32 UTC
