### ISSUE TITLE
iOS 13 deprecation issue - `setNetworkActivityIndicatorVisible`

### ISSUE THREAD

**Issue by hristo0624** [braintree/braintree-ios-drop-in#379] opened 2022-08-17 19:33 UTC
SDK iOS 13 deprecation issue

 - SDK/Library Version: 9.6.1
 - iOS Version: iOS 13.0
 - Xcode Version: Xcode 13.1
 - Integration type & version CocoaPods 1.11.3
 - Development Processor Type: Intel,
 

After integrating latest SDK version 9.6.1 and run on the xcode it shows following error on the BTVaultManagementViewController file.

Please let me know how to solve this issue.

![BraintreeDropin_iOS13](https://user-images.githubusercontent.com/86853979/185226762-7062629c-1603-45f1-a242-bd7706aff816.png)

**Comment by scannillo** [comment] 2022-08-30 12:34
Hi @hristo0624 - we are working on a fix for this and will have a PR up soon. In the meantime, you can turn off "Treat Warnings as Errors" in your Build Settings.

**Comment by scannillo** [comment] 2022-09-08 19:52
👋 Hi @hristo0624 - these deprecated method usages were removed in [v9.7.0](https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.7.0). Thank you for filing this issue!

**Closed by scannillo** 2022-09-08 19:52 UTC
Labels: bug

**Comment by nikitalpopov** [comment] 2022-09-13 19:21
Hi 😊
I still get error in XCode 14.0 and BraintreeDropIn 9.7.0. Any ideas why?

<img width="973" src="https://user-images.githubusercontent.com/6189087/189990878-d788fe20-a9d3-4d56-9a15-ae8c93ccc9ba.png">

**Comment by jaxdesmarais** [comment] 2022-10-13 19:16
Hello @nikitalpopov -

Would you mind clarifying the target iOS version of your application as well as the settings you have enabled? Xcode hitting the else block seems like it's more likely to be an Apple bug since that else block would be valid for targets lower than iOS 13.

**Comment by nikitalpopov** [comment] 2022-10-14 20:01
@jaxdesmarais iOS 13 is the target version so I guess that's the root cause of the issue.

**Comment by EdwinAlvrdo** [comment] 2023-01-08 17:27
I'm still have this issue, iOS 14 as target. XCode 14.2, Mac Silicon M1 pro. :( 

  - BraintreeDropIn (9.7.0):
  - Braintree/Core (5.19.0)

In my podfile i have just one dependency >> pod 'BraintreeDropIn'

My minimum deployment is 14.0, even in my podfile config

![Uploading Screenshot 2023-01-08 at 1.18.57 PM.png…]()

**Comment by andrii-lisovskiy** [comment] 2023-07-14 14:41
Still reproducing on my Xcode 14.3.1 and BraintreeDropIn (9.8.2)

**Comment by scannillo** [comment] 2023-07-17 20:29
👋 Hi @andrii-lisovskiy - can you open a new issue with steps to replicate / screen shots?

**Comment by andrii-lisovskiy** [comment] 2023-08-03 11:54
@scannillo Done -> [Issue](https://github.com/braintree/braintree-ios-drop-in/issues/421).
